"""Add type to Product

Revision ID: 2a22a1db7010
Revises: 
Create Date: 2024-05-18 20:29:09.635691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a22a1db7010'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_table('user',
    #sa.Column('id', sa.Integer(), nullable=False),
    #sa.Column('username', sa.String(length=100), nullable=False),
    #sa.Column('password', sa.String(length=100), nullable=False),
    #sa.Column('is_admin', sa.Boolean(), nullable=True),
    #sa.PrimaryKeyConstraint('id'),
    #sa.UniqueConstraint('username')
    #)
    #with op.batch_alter_table('product', schema=None) as batch_op:
        #batch_op.add_column(sa.Column('type', sa.Enum('refacciones', 'servicios', name='product_type'), nullable=False))

    # ### end Alembic commands ###
# ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('refacciones', 'servicios', name='product_type'), nullable=False, server_default='refacciones'))

    # Eliminar el valor predeterminado después de agregar la columna
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('refacciones', 'servicios', name='product_type'), nullable=True))
    # ### end Alembic commands ###

 # Actualizar valores existentes
    op.execute("UPDATE product SET type = 'refacciones' WHERE type IS NULL")

    # Hacer la columna NOT NULL
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('type', existing_type=sa.Enum('refacciones', 'servicios', name='product_type'), nullable=False)
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('type')

    #op.drop_table('user')
    # ### end Alembic commands ###
