"""Initial migration

Revision ID: 917d84df37a2
Revises: c0841df36530
Create Date: 2024-05-21 12:09:14.458239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '917d84df37a2'
down_revision = 'c0841df36530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_payment_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('payment_datetime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cash_payment_summary')
    # ### end Alembic commands ###
