"""Add status to service_order

Revision ID: c0841df36530
Revises: 0311c54f15c9
Create Date: 2024-05-20 22:29:46.547794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0841df36530'
down_revision = '0311c54f15c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_order', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
